# Generated by Django 5.2.5 on 2025-08-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='cover',
            field=models.ImageField(blank=True, upload_to='edcnews/images/%Y/%m/%d/'),
        ),
    ]
