# Generated by Django 5.2.5 on 2025-08-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcnews', '0002_noticia_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
