# Generated by Django 5.2.8 on 2025-11-29 23:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcnews', '0003_noticia_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=tinymce.models.HTMLField(),
        ),
    ]
