# Generated by Django 5.2.8 on 2025-11-29 23:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcnews', '0004_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
