# Generated by Django 6.0.2 on 2026-02-23 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('edcnews', '0006_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='authors.author'),
        ),
    ]
